festivals =[
    "Electric Daisy Carnival (EDC) Las Vegas",
    "Ultra Music Festival",
    "Coachella Valley Music and Arts Festival",
    "Lollapalooza",
    "HARD Summer",
    "Beyond Wonderland",
    "Movement Detroit",
    "Electric Forest",
    "Lost Lands",
    "Spring Awakening Music Festival",
    "Nocturnal Wonderland",
    "Lightning in a Bottle",
    "CRSSD Festival",
    "Dirtybird Campout",
    "Dreamstate",
    "Paradiso Festival",
    "Imagine Music Festival",
    "Electric Zoo",
    "Elements Music & Arts Festival",
    "Dancefestopia",
    "Global Dance Festival",
    "SnowGlobe Music Festival",
    "Okeechobee Music & Arts Festival",
    "Splash House",
    "Life is Beautiful",
    "BUKU Music + Art Project",
    "Second Sky Festival",
    "Holy Ship!",
    "Friendship",
    "Desert Hearts Festival",
    "Head in the Clouds Festival",
    "Portola Music Festival",
    "Goldrush Festival",
    "Breakaway Festival",
    "Cascade Equinox Festival",
    "Sacred Acre Festival",
    "Bass Canyon",
    "Dirtybird CampINN",
    "Firefly Music Festival",
    "Unison Festival",
    "Making Time",
    "Experts Only Festival",
    "Evolutions Festival",
    "Infrasound Equinox",
    "Neon Prairie",
    "Kinda Spoopy",
    "Goldrush: Neon Dreams",
    "Wakaan Music Festival",
    "Big Fam Music & Arts Festival",
    "Sacred Acre",
    "All My Friends Festival",
    "Governors Ball",
    "SXSW",
    "Hangout Music Festival",
    "Intersect Festival",
    "Arc Music Festival",
    "Dirtybird Campin'",
    "Day Trip Festival",
    "Same Same But Different",
    "Metamorphosis",
    "Deep Tropics",
    "Fire Lights Festival",
    "Sustain-Release",
    "Bonnaroo Music & Arts Festival",
    "Tomorrowland",
    "Rolling Loud",
    "Countdown",
    "Escape",
    "Decadence",
    "NorthCoast",
    "EDC",
    "Head In The Clouds",
    "Outsidelands",
    "KCon LA",
]
music_genres = [
    # Electronic Dance Music (EDM) Genres
    "Future Bass",
    "Melodic Dubstep",
    "Trance",
    "Progressive House",
    "Progressive Trance",
    "Melodic Bass",
    "Sadboi EDM",

    # Hip-Hop Genres
    "Mainstream Hip-Hop",
    "Old-School Hip-Hop",
    "Trap",
    "Alternative Hip-Hop",

    # R&B Genres
    "Contemporary R&B",
    "Alternative R&B",
    "K-R&B",
    "Soul",

    # Pop Genres
    "K-Pop",
    "Dance Pop",
    "Synth Pop",
    "Bubblegum Pop",
    "Electropop",
    "Tropical House",
    "Folk Pop",
    "Western Pop",

    # Reggae and Related Genres
    "Reggae",
    "Dancehall",
    "Soca",

    # Indie and Alternative Genres
    "Indie Pop",
    "Indie R&B",
    "Alternative Rock",
    "Emo",

    # Rock and Punk Genres
    "Emo Rock",
    "Punk",
    "Metalcore",
    "Post-Hardcore",
    "Visual Kei",
    "J-Rock",

    # World and Fusion Genres
    "Afrobeats",
    "Bollywood",
    "Chinese Folk",
    "Grime",
    "Latin Rock",
    "Lounge",
    "North African Funk",
    "Funk"
]