festival_to_description = {
    "Dive into the electrifying world of Electric Daisy Carnival (EDC) Las Vegas, the ultimate electronic dance music extravaganza featuring pulsating bass drops, headbanging rhythms, and thrilling DJ performances from world-class artists. Experience massive stages with fireworks, immersive art installations, and non-stop dancing under vibrant lights in a high-energy rave atmosphere that ignites excitement and unity among thousands of fans.": "Electric Daisy Carnival (EDC) Las Vegas",
    "Feel the adrenaline rush at Ultra Music Festival, a premier electronic dance music event bursting with exciting headbanging beats, energetic drops, and pulsating basslines from top global DJs. Revel in thrilling live sets, spectacular light shows, and a vibrant atmosphere filled with non-stop dancing, mosh pits, and fireworks, creating an unforgettable high-energy celebration of EDM culture.": "Ultra Music Festival",
    "Embark on a transformative journey at Coachella Valley Music and Arts Festival, a multi-genre spectacle blending indie, rock, pop, and electronic vibes with exciting performances that inspire headbanging and energetic dancing. Discover world-class artists on iconic stages amid stunning art installations, vibrant desert atmospheres, and thrilling light displays, fostering non-stop excitement and creative expression in a festival of epic proportions.": "Coachella Valley Music and Arts Festival",
    "Unleash your inner rockstar at Lollapalooza, a massive multi-genre festival delivering exciting headbanging concerts, pulsating beats, and high-energy performances from rock, hip-hop, and electronic icons. Immerse in a vibrant urban atmosphere with mosh pits, fireworks, art installations, and non-stop dancing, creating thrilling moments of unity and exhilaration across sprawling city parks.": "Lollapalooza",
    "Ignite your senses at HARD Summer, an explosive electronic dance music festival packed with headbanging bass drops, energetic DJ sets, and thrilling performances from cutting-edge artists. Dive into a vibrant rave atmosphere featuring pulsating rhythms, massive stages, light shows, and non-stop dancing that embodies the raw excitement of summer nightlife.": "HARD Summer",
    "Step into a whimsical realm at Beyond Wonderland, an enchanting electronic dance music festival offering headbanging adventures with pulsating beats, exciting DJ lineups, and immersive storytelling. Experience thrilling light displays, art installations, fireworks, and vibrant atmospheres that spark non-stop dancing and fantastical escapades in a wonderland of sound and visuals.": "Beyond Wonderland",
    "Embrace the origins of techno at Movement Detroit, a legendary electronic music festival pulsing with headbanging rhythms, energetic underground beats, and thrilling performances from techno pioneers. Immerse in a vibrant cityscape with non-stop dancing, innovative sound systems, and an atmosphere charged with excitement and innovation.": "Movement Detroit",
    "Wander through enchanted woods at Electric Forest, a multi-genre festival fusing jam bands and electronic music with exciting headbanging sets, pulsating bass, and thrilling live collaborations. Discover vibrant art installations, fireworks, light shows, and non-stop dancing in a magical forest atmosphere that fosters creativity and connection.": "Electric Forest",
    "Roar into the prehistoric vibes of Lost Lands, a dubstep haven delivering intense headbanging concerts, pulsating bass drops, and exciting performances from dubstep heavyweights. Experience thrilling mosh pits, massive stages, dinosaurs-themed art, fireworks, and a vibrant atmosphere of non-stop energy and bass-heavy exhilaration.": "Lost Lands",
    "Bloom into spring at Spring Awakening Music Festival, an electronic dance music event bursting with exciting headbanging beats, energetic DJ sets, and thrilling drops. Revel in vibrant park atmospheres, light shows, art installations, and non-stop dancing that signal the awakening of festival season with high-energy vibes.": "Spring Awakening Music Festival",
    "Venture into the night at Nocturnal Wonderland, a mystical electronic dance music festival featuring headbanging rhythms, pulsating beats, and exciting performances under starry skies. Immerse in thrilling light displays, immersive art, fireworks, and a vibrant rave atmosphere with non-stop dancing and enchanting themes.": "Nocturnal Wonderland",
    "Spark creativity at Lightning in a Bottle, a transformational festival blending electronic music with exciting headbanging sets, energetic beats, and thrilling DJ performances. Experience vibrant art installations, workshops, yoga, fireworks, and non-stop dancing in a sustainable, community-driven atmosphere of self-expression and unity.": "Lightning in a Bottle",
    "Ride the waves at CRSSD Festival, a house and techno paradise offering exciting headbanging grooves, pulsating rhythms, and thrilling sets from underground icons. Dive into a vibrant waterfront atmosphere with non-stop dancing, art, and an energetic blend of electronic sounds in a scenic urban setting.": "CRSSD Festival",
    "Camp out with the flock at Dirtybird Campout, a fun-filled house and techno festival featuring exciting headbanging beats, energetic DJ sets, and thrilling performances. Enjoy vibrant games, workshops, art, and non-stop dancing in a playful, community-oriented atmosphere that celebrates creativity and connection.": "Dirtybird Campout",
    "Enter a trance at Dreamstate, a euphoric electronic music festival delivering exciting headbanging melodies, pulsating basslines, and thrilling uplifting sets. Immerse in vibrant light shows, art installations, fireworks, and non-stop dancing in an atmosphere of pure trance energy and emotional highs.": "Dreamstate",
    "Ascend to paradise at Paradiso Festival, an electronic dance music utopia with exciting headbanging drops, energetic performances, and thrilling DJ lineups. Experience vibrant gorge views, light displays, art, fireworks, and non-stop dancing in a breathtaking natural amphitheater setting.": "Paradiso Festival",
    "Unleash your imagination at Imagine Music Festival, a multi-genre EDM event bursting with exciting headbanging concerts, pulsating beats, and thrilling aquatic-themed performances. Dive into vibrant art installations, fireworks, mosh pits, and non-stop dancing in an immersive fantasy world.": "Imagine Music Festival",
    "Go wild at Electric Zoo, New York's premier electronic music festival featuring exciting headbanging rhythms, energetic DJ sets, and thrilling bass drops. Roam vibrant zoo-themed stages with art, fireworks, light shows, and non-stop dancing in an urban wildlife adventure.": "Electric Zoo",
    "Harmonize with the elements at Elements Music & Arts Festival, a multi-genre event offering exciting headbanging sets, pulsating beats, and thrilling performances amid elemental themes. Experience vibrant art installations, workshops, fireworks, and non-stop dancing in a transformative, community-focused atmosphere.": "Elements Music & Arts Festival",
    "Groove in the heartland at Dancefestopia, an electronic dance music festival delivering exciting headbanging drops, energetic vibes, and thrilling DJ lineups. Immerse in vibrant forest settings, light shows, art, fireworks, and non-stop dancing for an unforgettable Midwestern rave.": "Dancefestopia",
    "Unite the world at Global Dance Festival, a multi-genre EDM event with exciting headbanging concerts, pulsating international beats, and thrilling performances. Experience vibrant cultural art, fireworks, light displays, and non-stop dancing in a global celebration of sound.": "Global Dance Festival",
    "Chill in the snow at SnowGlobe Music Festival, a winter electronic music wonderland featuring exciting headbanging sets, energetic drops, and thrilling DJ performances. Embrace vibrant snowy atmospheres, light shows, art, fireworks, and non-stop dancing amid Tahoe's majestic mountains.": "SnowGlobe Music Festival",
    "Discover serenity at Okeechobee Music & Arts Festival, a multi-genre event blending exciting headbanging electronic and jam sets with energetic performances. Immerse in vibrant art installations, workshops, fireworks, and non-stop dancing in a lush, transformative Florida paradise.": "Okeechobee Music & Arts Festival",
    "Make a splash at Splash House, a poolside electronic music festival with exciting headbanging house beats, energetic DJ sets, and thrilling vibes. Dive into vibrant resort atmospheres, light shows, art, and non-stop dancing under sunny Palm Springs skies.": "Splash House",
    "Celebrate life at Life is Beautiful, a multi-genre festival fusing exciting headbanging electronic and rock performances with energetic vibes and thrilling art. Experience vibrant downtown Las Vegas atmospheres, murals, fireworks, and non-stop inspiration in a city-wide block party.": "Life is Beautiful",
    "Unleash creativity at BUKU Music + Art Project, a multi-genre event delivering exciting headbanging bass, energetic hip-hop, and thrilling electronic sets. Immerse in vibrant New Orleans warehouses, art installations, graffiti, fireworks, and non-stop urban exploration.": "BUKU Music + Art Project",
    "Soar higher at Second Sky Festival, Porter Robinson's curated electronic music event with exciting headbanging drops, energetic melodies, and thrilling performances. Experience vibrant immersive worlds, light shows, art, fireworks, and non-stop emotional highs in a dreamlike setting.": "Second Sky Festival",
    "Set sail on Holy Ship!, a floating electronic music festival cruising with exciting headbanging beats, energetic DJ sets, and thrilling ocean vibes. Dive into vibrant ship parties, art, fireworks, and non-stop dancing on high seas adventures.": "Holy Ship!",
    "Bond on Friendship, a cruise-based electronic music festival featuring exciting headbanging rhythms, energetic collaborations, and thrilling performances. Experience vibrant onboard art, fireworks, light shows, and non-stop dancing in a floating community of friends.": "Friendship",
    "Feel the love at Desert Hearts Festival, a house and techno gathering with exciting headbanging grooves, energetic vibes, and thrilling continuous sets. Immerse in vibrant desert atmospheres, art installations, fireworks, and non-stop dancing in a one-stage family reunion.": "Desert Hearts Festival",
    "Float above at Head in the Clouds Festival, an Asian music showcase blending exciting headbanging K-pop and hip-hop with energetic performances. Experience vibrant cultural art, food, fireworks, and non-stop dancing in a celebration of Asian excellence.": "Head in the Clouds Festival",
    "Innovate at Portola Music Festival, an electronic music event delivering exciting headbanging beats, energetic underground sets, and thrilling vibes. Immerse in vibrant San Francisco warehouses, art, light shows, and non-stop dancing in an industrial playground.": "Portola Music Festival",
    "Strike gold at Goldrush Festival, a multi-genre EDM event with exciting headbanging bass, energetic drops, and thrilling performances. Experience vibrant Wild West themes, art installations, fireworks, mosh pits, and non-stop dancing in Arizona's desert.": "Goldrush Festival",
    "Break free at Breakaway Festival, a multi-genre music event featuring exciting headbanging electronic and pop sets with energetic vibes. Immerse in vibrant stadium atmospheres, light shows, art, fireworks, and non-stop dancing across multiple cities.": "Breakaway Festival",
    "Balance energies at Cascade Equinox Festival, a multi-genre event blending jam, electronic, funk, soul, and bluegrass with exciting headbanging sets and energetic performances. Experience vibrant art installations, workshops, fireworks, and non-stop dancing in Oregon's high desert.": "Cascade Equinox Festival",
    "Awaken spirits at Sacred Acre Festival, an electronic bass music festival with headbanging dubstep drops, energetic vibes, and thrilling laser shows. Immerse in vibrant Alaskan wilderness, art, excursions, fireworks, and non-stop dancing under northern skies.": "Sacred Acre Festival",
    "Drop into the gorge at Bass Canyon, a bass music festival roaring with exciting headbanging dubstep, energetic riddim, and thrilling performances. Experience vibrant canyon views, massive stages, fireworks, mosh pits, and non-stop bass in Washington's natural amphitheater.": "Bass Canyon",
    "Nest with the flock at Dirtybird CampINN, a house and techno resort takeover with exciting headbanging grooves, energetic DJ sets, and thrilling pool parties. Enjoy vibrant games, workshops, art, and non-stop dancing in a luxurious, community-driven escape.": "Dirtybird CampINN",
    "Illuminate the night at Firefly Music Festival, a multi-genre event glowing with exciting headbanging electronic and rock sets, energetic performances. Experience vibrant woodlands, art installations, fireworks, mosh pits, and non-stop dancing in Delaware's enchanted forests.": "Firefly Music Festival",
    "Unite in harmony at Unison Festival, a transformational event fostering connection through exciting electronic sets, energetic expressions, and thrilling workshops. Embrace vibrant community vibes, art, yoga, and non-stop dancing in a heart-centered, sustainable space.": "Unison Festival",
    "Craft memories at Making Time, an electronic festival pulsing with exciting headbanging house and techno, energetic underground beats, and thrilling vibes. Immerse in vibrant curated atmospheres, art, light shows, and non-stop dancing in intimate settings.": "Making Time",
    "Excel in excellence at Experts Only Festival, a dance music showcase with exciting headbanging house, energetic techno, and thrilling performances. Experience vibrant stages, light displays, art, fireworks, and non-stop dancing curated by industry experts.": "Experts Only Festival",
    "Evolve together at Evolutions Festival, a multi-genre event inspiring growth through exciting headbanging sets, energetic jams, and thrilling collaborations. Immerse in vibrant art, workshops, fireworks, and non-stop dancing in a transformative community.": "Evolutions Festival",
    "Dive deep at Infrasound Equinox, a bass-heavy festival rumbling with exciting headbanging dubstep, energetic experimental sounds, and thrilling performances. Experience vibrant forests, art installations, fireworks, mosh pits, and non-stop bass in Minnesota's woods.": "Infrasound Equinox",
    "Glow in the neon at Neon Prairie, a vibrant multi-genre festival illuminating exciting headbanging electronic sets, energetic funk, and thrilling vibes. Immerse in luminous art, light shows, fireworks, and non-stop dancing under prairie skies.": "Neon Prairie",
    "Get spooky at Kinda Spoopy, a Halloween-themed festival blending exciting headbanging beats, energetic performances, and thrilling chills. Experience vibrant costumes, art, fireworks, mosh pits, and non-stop dancing in a fun, festive atmosphere.": "Kinda Spoopy",
    "Dream in neon at Goldrush: Neon Dreams, an EDM festival glowing with exciting headbanging bass, energetic drops, and thrilling DJ sets. Immerse in vibrant Wild West neon themes, art, fireworks, and non-stop dancing under desert lights.": "Goldrush: Neon Dreams",
    "Awaken the weird at Wakaan Music Festival, a bass music haven roaring with exciting headbanging dubstep, energetic experimental vibes, and thrilling performances. Experience vibrant Ozark mountains, art installations, fireworks, mosh pits, and non-stop bass.": "Wakaan Music Festival",
    "Bond as family at Big Fam Music & Arts Festival, a multi-genre camping event fostering exciting headbanging electronic and jam sets with energetic vibes. Immerse in vibrant Michigan woods, art, workshops, fireworks, and non-stop dancing in community spirit.": "Big Fam Music & Arts Festival",
    "Sanctify the bass at Sacred Acre, an electronic festival pulsing with exciting headbanging dubstep, energetic beats, and thrilling laser shows. Experience vibrant Alaskan adventures, art, excursions, fireworks, and non-stop dancing in pristine wilderness.": "Sacred Acre",
    "Reunite with pals at All My Friends Festival, an emo and pop-punk bash rocking with exciting headbanging concerts, energetic anthems, and thrilling mosh pits. Experience vibrant nostalgia, art, fireworks, and non-stop singing in a celebratory atmosphere.": "All My Friends Festival",
    "Rule the island at Governors Ball, a multi-genre festival commanding exciting headbanging rock and electronic sets with energetic vibes. Immerse in vibrant New York parks, art, food, fireworks, and non-stop dancing in urban energy.": "Governors Ball",
    "Innovate at SXSW, a multi-genre showcase festival buzzing with exciting headbanging indie and electronic performances, energetic emerging talent. Experience vibrant Austin streets, film, tech, art, fireworks, and non-stop discovery in a creative hub.": "SXSW",
    "Chill on the beach at Hangout Music Festival, a multi-genre seaside event with exciting headbanging electronic and rock sets, energetic waves. Experience vibrant Gulf shores, art, fireworks, mosh pits, and non-stop dancing in sandy paradise.": "Hangout Music Festival",
    "Converge at Intersect Festival, a multi-genre event blending exciting headbanging electronic and rock performances with innovative vibes. Immerse in vibrant tech-infused art, light shows, fireworks, and non-stop dancing in a futuristic fusion.": "Intersect Festival",
    "Arch into house at Arc Music Festival, a techno and house celebration pulsing with exciting headbanging grooves, energetic underground sets. Experience vibrant Chicago parks, art, fireworks, light shows, and non-stop dancing in Windy City style.": "Arc Music Festival",
    "Camp with birds at Dirtybird Campin', a house and techno getaway with exciting headbanging beats, energetic DJ sets, and thrilling fun. Enjoy vibrant activities, art, workshops, and non-stop dancing in a playful, flock-friendly atmosphere.": "Dirtybird Campin'",
    "Journey daily at Day Trip Festival, an electronic house event offering exciting headbanging grooves, energetic vibes, and thrilling daytime sets. Immerse in vibrant urban escapes, art, light shows, and non-stop dancing under sunny skies.": "Day Trip Festival",
    "Embrace uniqueness at Same Same But Different, a multi-genre festival fostering exciting headbanging electronic and funk sets with energetic vibes. Experience vibrant lake beaches, art, workshops, fireworks, and non-stop dancing in community harmony.": "Same Same But Different",
    "Transform at Metamorphosis, an electronic festival unveiling exciting headbanging bass, energetic drops, and thrilling performances. Immerse in vibrant amphitheaters, art installations, light shows, fireworks, and non-stop evolution in Orlando's heat.": "Metamorphosis",
    "Dive deep at Deep Tropics, a house and bass festival pulsing with exciting headbanging rhythms, energetic sets, and thrilling vibes. Experience vibrant sustainable parks, art, workshops, fireworks, and non-stop dancing in eco-conscious energy.": "Deep Tropics",
    "Ignite passions at Fire Lights Festival, an electronic bass and funk event blazing with exciting headbanging drops, energetic performances. Experience vibrant forests, art installations, fire shows, fireworks, and non-stop dancing in New York's woods.": "Fire Lights Festival",
    "Sustain the vibe at Sustain-Release, an electronic techno festival flowing with exciting headbanging grooves, energetic underground sets. Immerse in vibrant camps, art, light shows, and non-stop dancing in New York's intimate, experimental spaces.": "Sustain-Release",
    "Roo the day at Bonnaroo Music & Arts Festival, a multi-genre extravaganza with exciting headbanging electronic and rock sets, energetic jams. Experience vibrant Tennessee farms, art, comedy, fireworks, mosh pits, and non-stop dancing in communal bliss.": "Bonnaroo Music & Arts Festival",
    "Dream tomorrow at Tomorrowland, the world's premier electronic music festival exploding with exciting headbanging drops, energetic anthems, and thrilling spectacles. Immerse in vibrant fantasy realms, massive stages, fireworks, art, and non-stop dancing in global unity.": "Tomorrowland",
    "Roll deep at Rolling Loud, the ultimate hip-hop festival booming with exciting headbanging trap beats, energetic rap battles, and thrilling cyphers. Experience vibrant urban vibes, graffiti art, mosh pits, fireworks, and non-stop hyped energy.": "Rolling Loud",
    "Count down to ecstasy at Countdown, a New Year's electronic festival igniting with exciting headbanging bass, energetic drops, and thrilling midnight vibes. Experience vibrant rave atmospheres, light shows, fireworks, art, and non-stop dancing into the new year.": "Countdown",
    "Break free at Escape, a Halloween electronic festival haunting with exciting headbanging beats, energetic techno, and thrilling spooky vibes. Immerse in vibrant immersive worlds, light shows, art, fireworks, and non-stop dancing in costumed chaos.": "Escape",
    "Indulge in Decadence, a New Year's electronic festival overflowing with exciting headbanging drops, energetic house, and thrilling countdowns. Experience vibrant arena atmospheres, light shows, fireworks, art, and non-stop dancing into luxurious new beginnings.": "Decadence",
    "Coast north at NorthCoast, a multi-genre festival cruising with exciting headbanging electronic and hip-hop sets, energetic vibes. Experience vibrant Chicago stadiums, art, fireworks, mosh pits, and non-stop dancing in Midwestern style.": "NorthCoast",
    "Enter the circuit at EDC, the flagship electronic dance music festival exploding with exciting headbanging bass, energetic DJ sets, and thrilling spectacles. Experience vibrant speedways, massive stages, fireworks, art installations, and non-stop dancing in electric daisy fields.": "EDC",
    "Cloud surf at Head In The Clouds, an Asian music festival soaring with exciting headbanging K-pop and hip-hop, energetic performances. Experience vibrant cultural fusions, food, art, fireworks, and non-stop dancing in elevated celebrations.": "Head In The Clouds",
    "Venture outside at Outside Lands, a multi-genre festival blooming with exciting headbanging electronic and rock sets, energetic vibes. Experience vibrant San Francisco parks, art, food, wine, fireworks, and non-stop dancing in foggy wonderlands.": "Outside Lands",
    "Connect at KCON LA, a K-pop convention festival buzzing with exciting headbanging pop performances, energetic idols, and thrilling fan engagements. Experience vibrant Korean culture, food, beauty, art, and non-stop dancing in Hallyu waves.": "KCon LA"
}

music_genres = [
    # Electronic Dance Music (EDM) Genres
    "Future Bass",
    "Melodic Dubstep",
    "Trance",
    "Progressive House",
    "Progressive Trance",
    "Melodic Bass",
    "Sadboi EDM",

    # Hip-Hop Genres
    "Mainstream Hip-Hop",
    "Old-School Hip-Hop",
    "Trap",
    "Alternative Hip-Hop",

    # R&B Genres
    "Contemporary R&B",
    "Alternative R&B",
    "K-R&B",
    "Soul",

    # Pop Genres
    "K-Pop",
    "Dance Pop",
    "Synth Pop",
    "Bubblegum Pop",
    "Electropop",
    "Tropical House",
    "Folk Pop",
    "Western Pop",

    # Reggae and Related Genres
    "Reggae",
    "Dancehall",
    "Soca",

    # Indie and Alternative Genres
    "Indie Pop",
    "Indie R&B",
    "Alternative Rock",
    "Emo",

    # Rock and Punk Genres
    "Emo Rock",
    "Punk",
    "Metalcore",
    "Post-Hardcore",
    "Visual Kei",
    "J-Rock",

    # World and Fusion Genres
    "Afrobeats",
    "Bollywood",
    "Chinese Folk",
    "Grime",
    "Latin Rock",
    "Lounge",
    "North African Funk",
    "Funk"
]