descriptions_to_aliases = {
    # Restaurants
    "Restaurants": "restaurants",
    "American (Traditional)": "tradamerican",
    "American (New)": "newamerican",
    "Burgers": "burgers",
    "Pizza": "pizza",
    "Sushi Bars": "sushi",
    "Italian": "italian",
    "Chinese": "chinese",
    "Japanese": "japanese",
    "Korean": "korean",
    "Thai": "thai",
    "Vietnamese": "vietnamese",
    "Mexican": "mexican",
    "Indian": "indpak",
    "Mediterranean": "mediterranean",
    "Middle Eastern": "mideastern",
    "Seafood": "seafood",
    "Steakhouses": "steak",
    "Barbecue": "bbq",
    "Breakfast & Brunch": "breakfast_brunch",
    "Cafes": "cafes",
    "Bakeries": "bakeries",
    "Coffee & Tea": "coffeetea",
    "Desserts": "desserts",
    "Fast Food": "hotdogs",
    "Vegetarian": "vegetarian",
    "Vegan": "vegan",
    "Gluten-Free": "gluten_free",

    # Nightlife / Clubs / Bars
    "Bars": "bars",
    "Nightlife": "nightlife",
    "Night Clubs": "nightclubs",
    "Dance Clubs": "danceclubs",
    "Lounges": "lounges",
    "Comedy Clubs": "comedyclubs",
    "Sports Bars": "sportsbars",
    "Tiki Bars": "tikibars",
    "Wine Bars": "winebars",
    "Cocktail Bars": "cocktailbars",
    "Dive Bars": "divebars",
    "Speakeasies": "speakeasies",

    # Beverage Shops
    "Bubble Tea": "bubbletea",
    "Juice Bars & Smoothies": "juicebars",
    "Cideries": "cideries",
    "Distilleries": "distilleries",
    "Breweries": "breweries",
    "Wineries": "wineries",
    "Tea Rooms": "tearooms",

    # Activities / Entertainment
    "Golf": "golf",
    "Karaoke": "karaoke",
    "Bowling": "bowling",
    "Amusement Parks": "amusementparks",
    "Aquariums": "aquariums",
    "Zoos": "zoos",
    "Hiking": "hiking",
    "Parks": "parks",
    "Beaches": "beaches",
    "Museums": "museums",
    "Art Galleries": "artgalleries",
    "Theater": "theater",
    "Live Music": "livemusic",

    # General Viewpoints / Sightseeing
    "Scenic Views": "parks",
}
